excluded:
  - Carthage
  - Pods

force_try:
  severity: warning

force_cast:
  severity: warning

file_length: 500

type_body_length: 300

line_length:
  warning: 200
  ignores_comments: true
  ignores_interpolated_strings: true

function_body_length: 125

large_tuple:
  warning: 3
  error: 4

identifier_name:
  excluded:
    - id

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - multiline_parameters
  - operator_usage_whitespace
  - private_outlet
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - implicit_return
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - let_var_whitespace
